---
title: "Costa Rica Rhizosphere Manipulation Effect Sizes"
author: "Kenna Rewcastle"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, include=FALSE}
library(dplyr)
library(vegan)
library(ggplot2)
library(tidyr)
library(reshape2)
library(stringr)
```

```{r input_data, include=FALSE}
# 13C-CO2
  CO2_13C<-read.csv("Costa Rica Master sheet annotated.csv")
  CO2_13C<-data.frame("Core_ID"=CO2_13C$core_ID,"Tree"=CO2_13C$Tree_species,"Rhizosphere_Manipulation"=as.factor(CO2_13C$Exclusion),"Day2_D13_CO2"=CO2_13C$d13_d2,"Day9_D13_CO2"=CO2_13C$d13_d9,"Substrate"=CO2_13C$Isotope_label)
  
  CO2_13C$Tree[which(CO2_13C$Tree=="Goeth")]<-"G"
  CO2_13C$Tree[which(CO2_13C$Tree=="Penta")]<-"P"
  
  leaf_CO2<-filter(CO2_13C,Substrate=="L")
  leaf_CO2<-leaf_CO2[,c(1,2,3,5)]
  
  starch_CO2<-filter(CO2_13C,Substrate=="S")
  starch_CO2<-starch_CO2[,c(1:4)]

# 13C-PLFA
  data<-read.csv("FINAL_PLFA_with_metadata.csv")
  data<-data[,2:15] # Gets rid of ID column
  data<-filter(data,Microbial_Group!="standard")
  data$Rhizosphere_Manipulation<-as.factor(data$Rhizosphere_Manipulation)
  data$umol_FAME<-data$nmol_FAME_per_g_soil/1000
  
  ## Simplify the microbial groupings
  data_trim<-data.frame("Sample_Name"=data[,1],"Tree"=data[,2],"Rhizosphere_Manipulation"=data[,3],"Substrate_Type"=data[,4],"Microbial_Group"=data[,14],"d13"=data[,9])
  
  data_wide<-dcast(data_trim,Sample_Name+Tree+Rhizosphere_Manipulation+Substrate_Type ~ Microbial_Group, value.var="d13", fun.aggregate=mean, na.rm=TRUE)
  
  is.nan.data.frame <- function(x)
    do.call(cbind, lapply(x, is.nan))
  data_wide[is.nan(data_wide)] <- NA
  
    ### Take mean of narrow groups to yield FUNGI, BACTERIA, ALL_MICROBE groups
    for (i in 1:nrow(data_wide)) {
      data_wide$BACTERIA[i]<-mean(c(data_wide$bacteria[i],data_wide$`gram+bacteria`[i],data_wide$`gram-bacteria`[i]),na.rm=TRUE)
      data_wide$FUNGI[i]<-mean(c(data_wide$AMF[i],data_wide$fungi[i]),na.rm=TRUE)
      data_wide$ALL_MICROBES[i]<-mean(c(data_wide$AMF[i],data_wide$bacteria[i],data_wide$fungi[i],data_wide$general[i],data_wide$`gram-bacteria`[i],data_wide$`gram+bacteria`[i],data_wide$protozoa[i]),na.rm=TRUE)
      }

  data_wide<-data_wide[,c(1,2,3,4,5,12,13,14)] # Trim down to broader groups
  data<-melt(data_wide,value.name="d13",id.vars=c("Sample_Name","Rhizosphere_Manipulation","Tree","Substrate_Type"))
  names(data)[5]<-"Microbial_Group"
  
  ## Add a column for tree ID
  data$Tree_ID<-substr(data$Sample_Name,1,5)
  
  ## Formatting requirements
  PLFA_13C<-data.frame("Core_ID"=data$Sample_Name,"Tree"=data$Tree,"Rhizosphere_Manipulation"=data$Rhizosphere_Manipulation,"D13_PLFA"=data$d13,"Microbial_Group"=data$Microbial_Group,"Substrate"=data$Substrate_Type)
  substring(PLFA_13C$Core_ID,3,3)<-"_"
  substring(PLFA_13C$Core_ID,6,6)<-"_"
  
  ## Separate leaf and starch datasets
  leaf_PLFA<-filter(PLFA_13C,Substrate=="L")
  leaf_PLFA<-leaf_PLFA[,1:5]
  starch_PLFA<-filter(PLFA_13C,Substrate=="S")
  starch_PLFA<-starch_PLFA[,1:5]
  
  ## AMF
  leaf_AMF<-filter(leaf_PLFA,Microbial_Group=="AMF")
  leaf_AMF<-leaf_AMF[,1:4]
  starch_AMF<-filter(starch_PLFA,Microbial_Group=="AMF")
  starch_AMF<-starch_AMF[,1:4]
  
  ## Fungi
  leaf_fungi<-filter(leaf_PLFA,Microbial_Group=="FUNGI")
  leaf_fungi<-leaf_fungi[,1:4]
  starch_fungi<-filter(starch_PLFA,Microbial_Group=="FUNGI")
  starch_fungi<-starch_fungi[,1:4]
  
  ## Bacteria
  leaf_bact<-filter(leaf_PLFA,Microbial_Group=="BACTERIA")
  leaf_bact<-leaf_bact[,1:4]
  starch_bact<-filter(starch_PLFA,Microbial_Group=="BACTERIA")
  starch_bact<-starch_bact[,1:4]
  
  ## All Microbes
  leaf_allmicro<-filter(leaf_PLFA,Microbial_Group=="ALL_MICROBES")
  leaf_allmicro<-leaf_allmicro[,1:4]
  starch_allmicro<-filter(starch_PLFA,Microbial_Group=="ALL_MICROBES")
  starch_allmicro<-starch_allmicro[,1:4]
  
# 13C Specific Respiration
  SpecResp_13C<-read.csv("Final_Specific_Respiration_Data.csv")
  
  ## Formatting requirements
  substring(SpecResp_13C$Core_ID,3,3)<-"_"
  substring(SpecResp_13C$Core_ID,6,6)<-"_"
  SpecResp_13C<-data.frame("Core_ID"=SpecResp_13C$Core_ID,"Tree"=SpecResp_13C$Tree_Species,"Rhizosphere_Manipulation"=as.factor(SpecResp_13C$Mesh_Type),"SpecResp_ug_CO2_FAME"=SpecResp_13C$Specific_Respiration_CO2_FAME,"Substrate"=SpecResp_13C$Label_Type)
  
  ## Separate leaf and starch
  leaf_SpecResp<-filter(SpecResp_13C,Substrate=="L")
  leaf_SpecResp<-leaf_SpecResp[,1:4]
  starch_SpecResp<-filter(SpecResp_13C,Substrate=="S")
  starch_SpecResp<-starch_SpecResp[,1:4]

# Background respiration
  
  
  
PLFA<-
SpecResp<-
```


```{r function_mean_rhizo_calc, include=FALSE}
########################################################################
# FUNCTION: Rhizo_Variable_Means
# Calculates mean, sd, n for each rhizosphere manipulation treatment, flexible response variable, in order to calculate standardize mean differences
# input: data = data frame with the following columns: Core_ID,Tree,Rhizosphere_Manipulation,Var (Var = response variable)
# output: data frame with above summary statistics
#-----------------------------------------------------------------------

Rhizo_Variable_Means<-function(data) {
  
  names(data)<-c("Core_ID","Tree","Rhizosphere_Manipulation",paste(names(data)[4]))
  data$Rhizosphere_Manipulation<-as.factor(data$Rhizosphere_Manipulation)
  
  # Vectors for sample size of each rhizosphere manipulation treatment group
  n1<-c()
  n2<-c()
  n3<-c()
  
  # Vectors for mean of each treatment group
  m1<-c()
  m2<-c()
  m3<-c()
  
  # Vectors for standard deviation of each treatment group
  sd1<-c()
  sd2<-c()
  sd3<-c()
  
  # Creating separate data frames for each tree species
  goeth<-filter(data,Tree=="G")
  penta<-filter(data,Tree=="P")
  
  ## NOTE: row 1 will contain Goethalsia data, row 2 will contain Pentaclethra data
  
  # Calculate stats for control group +R+M (rhizosphere exclusion 3)
    ## GOETHALSIA
    n3[1]<-nrow(goeth[which(goeth$Rhizosphere_Manipulation=="3"),])
    m3[1]<-mean(goeth[which(goeth$Rhizosphere_Manipulation=="3"),4],na.rm=TRUE)
    sd3[1]<-sd(goeth[which(goeth$Rhizosphere_Manipulation=="3"),4],na.rm=TRUE)
    
    ## PENTACLETHRA
    n3[2]<-nrow(penta[which(penta$Rhizosphere_Manipulation=="3"),])
    m3[2]<-mean(penta[which(penta$Rhizosphere_Manipulation=="3"),4],na.rm=TRUE)
    sd3[2]<-sd(penta[which(penta$Rhizosphere_Manipulation=="3"),4],na.rm=TRUE)
  
  # Calculate stats for +R-M treatment (rhizosphere exclusion 2)
    ## GOETHALSIA
    n2[1]<-nrow(goeth[which(goeth$Rhizosphere_Manipulation=="2"),])
    m2[1]<-mean(goeth[which(goeth$Rhizosphere_Manipulation=="2"),4],na.rm=TRUE)
    sd2[1]<-sd(goeth[which(goeth$Rhizosphere_Manipulation=="2"),4],na.rm=TRUE)
    
    ## PENTACLETHRA
    n2[2]<-nrow(penta[which(penta$Rhizosphere_Manipulation=="2"),])
    m2[2]<-mean(penta[which(penta$Rhizosphere_Manipulation=="2"),4],na.rm=TRUE)
    sd2[2]<-sd(penta[which(penta$Rhizosphere_Manipulation=="2"),4],na.rm=TRUE)
  
 # Calculate stats for -R-M treatment (rhizosphere exclusion 1)
    ## GOETHALSIA
    n1[1]<-nrow(goeth[which(goeth$Rhizosphere_Manipulation=="1"),])
    m1[1]<-mean(goeth[which(goeth$Rhizosphere_Manipulation=="1"),4],na.rm=TRUE)
    sd1[1]<-sd(goeth[which(goeth$Rhizosphere_Manipulation=="1"),4],na.rm=TRUE)
    
    ## PENTACLETHRA
    n1[2]<-nrow(penta[which(penta$Rhizosphere_Manipulation=="1"),])
    m1[2]<-mean(penta[which(penta$Rhizosphere_Manipulation=="1"),4],na.rm=TRUE)
    sd1[2]<-sd(penta[which(penta$Rhizosphere_Manipulation=="1"),4],na.rm=TRUE)
  
  outDat<-data.frame("Tree_Species"=c("G","P"),n3,m3,sd3,n2,m2,sd2,n1,m1,sd1)  
  
  return(outDat)
}

```

```{r effect_size_inputs}
# 13C-CO2
leaf_CO2_dat<-

leaf_CO2_SMD_in<-
```

